const topWidth = 1728;
const topHeight = 1117;

export default {
  prop1: {
    tip: "Proposta 1",
    title: "Xarxa Llibres",
    text: "Helloo",
    picture: {
      // 1728 - 100, 1117
      src: "/images/proposals/books.jpg",
      width: (449 * 100) / topWidth,
      top: (995 * 100) / topWidth,
      left: (616 * 100) / topHeight,
      delay: 2,
      strength: 30,
      origin: "right bottom",
    },
  },
  prop2: {
    tip: "Proposta 2",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (241 * 100) / topWidth,
      top: (114 * 100) / topHeight,
      left: (95 * 100) / topWidth,
      delay: 4.5,
      strength: 40,
    },
  },
  prop3: {
    tip: "Proposta 3",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (355 * 100) / topWidth,
      top: (621 * 100) / topHeight,
      left: (262 * 100) / topWidth,
      delay: 7,
      strength: 25,
    },
  },
  prop4: {
    tip: "Proposta 4",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (259 * 100) / topWidth,
      top: (194 * 100) / topHeight,
      left: (576 * 100) / topWidth,
      delay: 10.5,
      strength: 30,
    },
  },
  prop5: {
    tip: "Proposta 5",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (211 * 100) / topWidth,
      top: (312 * 100) / topHeight,
      left: (1156 * 100) / topWidth,
      delay: 14,
      strength: 30,
      origin: "right bottom",
    },
  },
  prop6: {
    tip: "Proposta 6",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (100 * 100) / topWidth,
      top: (166 * 100) / topHeight,
      left: (1377 * 100) / topWidth,
      delay: 17,
      strength: 40,
    },
  },
  prop7: {
    tip: "Proposta 7",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (180 * 100) / topWidth,
      top: (463 * 100) / topHeight,
      left: (1506 * 100) / topWidth,
      delay: 22,
      strength: 40,
    },
  },
  prop8: {
    tip: "Proposta 8",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (180 * 100) / topWidth,
      top: (62 * 100) / topHeight,
      left: (985 * 100) / topWidth,
      delay: 28,
      strength: 30,
    },
  },
  prop9: {
    tip: "Proposta 9",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (380 * 100) / topWidth,
      top: (362 * 100) / topHeight,
      left: (695 * 100) / topWidth,
      delay: 24,
      strength: 16,
    },
  },
  prop10: {
    tip: "Proposta 10",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    picture: {
      src: "/images/proposals/books.jpg",
      width: (120 * 100) / topWidth,
      top: (52 * 100) / topHeight,
      left: (495 * 100) / topWidth,
      delay: 29,
      strength: 50,
    },
  },
};
