const topWidth = 1728;
const topHeight = 1477;

export default {
  prop1: {
    tip: "Proposta 1",
    title: "Xarxa Llibres",
    text: "Helloo",
    category: "done",
    picture: {
      // 1728 - 100, 1117
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (449 * 100) / topWidth,
      top: (995 * 100) / topWidth,
      left: (616 * 100) / topHeight,
      minWidth: "225px",
      delay: 2,
      strength: 5,
      origin: "right bottom",
    },
  },
  prop2: {
    tip: "Proposta 2",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "to_be_done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (241 * 100) / topWidth,
      top: (234 * 100) / topHeight,
      left: (95 * 100) / topWidth,
      minWidth: "140px",
      delay: 4.5,
      strength: 8,
    },
  },
  prop3: {
    tip: "Proposta 3",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (241 * 100) / topWidth,
      top: (312 * 100) / topHeight,
      left: (1156 * 100) / topWidth,
      minWidth: "110px",
      delay: 7,
      strength: 7,
      origin: "right bottom",
    },
  },
  prop4: {
    tip: "Proposta 4",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "to_be_done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (325 * 100) / topWidth,
      top: (821 * 100) / topHeight,
      left: (262 * 100) / topWidth,
      minWidth: "100px",
      delay: 9,
      strength: 3.5,
    },
  },
  prop5: {
    tip: "Proposta 5",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (269 * 100) / topWidth,
      top: (194 * 100) / topHeight,
      left: (576 * 100) / topWidth,
      minWidth: "150px",
      delay: 14,
      strength: 5,
    },
  },
  prop6: {
    tip: "Proposta 6",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "to_be_done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (190 * 100) / topWidth,
      top: (166 * 100) / topHeight,
      left: (1377 * 100) / topWidth,
      minWidth: "90px",
      delay: 16,
      strength: 5,
    },
  },
  prop7: {
    tip: "Proposta 7",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (180 * 100) / topWidth,
      top: (423 * 100) / topHeight,
      left: (1506 * 100) / topWidth,
      minWidth: "110px",
      delay: 18.5,
      strength: 3.5,
    },
  },
  prop8: {
    tip: "Proposta 8",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "to_be_done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (200 * 100) / topWidth,
      top: (1062 * 100) / topHeight,
      left: (1385 * 100) / topWidth,
      minWidth: "160px",
      delay: 22,
      strength: 7,
    },
  },
  prop9: {
    tip: "Proposta 9",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (380 * 100) / topWidth,
      top: (362 * 100) / topHeight,
      left: (695 * 100) / topWidth,
      minWidth: "120px",
      delay: 24,
      strength: 10,
    },
  },
  prop10: {
    tip: "Proposta 10",
    title: "Haver construït 103 escoeles",
    text: "Helloo",
    category: "to_be_done",
    picture: {
      src: "/images/proposals/books.jpg",
      alt: "",
      width: (320 * 100) / topWidth,
      top: (640 * 100) / topHeight,
      left: (1450 * 100) / topWidth,
      minWidth: "80px",
      delay: 26,
      strength: 8,
    },
  },
};
